### ISSUE TITLE
Debugging fails with "Cannot insert breakpoint -1"

### ISSUE THREAD

**Issue by horaciojcfilho** [Microsoft/VSLinux#119]
Debugging a C++ Linux application created from scratch raises the following errors:
- Cannot insert breakpoint -1.
- Cannot access memory at address 0x570.

Expected results:
_Debugger run fine and reach any breakpoint._

Actual results:
_=thread-group-added,id="i1" GNU gdb (GDB) 7.9 Copyright (C) 2015 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. Type "show copying" and "show warranty" for details. This GDB was configured as "--host=i686-pc-mingw32 --target=x86_64-linux-gnu". Type "show configuration" for configuration details. For bug reporting instructions, please see: <http://www.gnu.org/software/gdb/bugs/>. Find the GDB manual and other documentation resources online at: <http://www.gnu.org/software/gdb/documentation/>. For help, type "help". Type "apropos word" to search for commands related to "word". Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file._

VS 2017 preview
VMware machine running Ubuntu 17.04
Windows 10.0.14393

**Comment by gift0125** [comment]
It seems that the gdb version of VSLinux is 7.9, but the gdb version of ubuntu 17.04 is 7.12 which is higher than VSLinux.It's not compatible.

**Comment by robotdad** [comment]
We are looking at this, something seems to have impacted us beginning with Ubuntu 16.10

**Comment by stanthomas** [comment]
I'm seeing this after upgrading to Debian 9 (Stretch) which has gcc 6.3.0 and gdb 7.12.0.

Fails in gdbserver mode with error described in VS2017 15.3.0 Preview 2.1 / VCLinux 1.0.7 but works in VS2017 15.2 (26430.14) / VCLinux 1.0.6.
gdb mode works everywhere, although no console input of course.

**Comment by shlublu** [comment]
Same here with VC2015 / VCLinux 1.0.7 /  Ubuntu 16.04.2 (gdb version: 7.11.1).

I initially opened [a StackOverflow question](https://stackoverflow.com/questions/44883007/visual-studio-2015-linux-extension-1-0-7-breakpoints-are-ignored) for this (thanks @stanthomas for the help!).

**Comment by GoodJoey** [comment]
hi, robotdad, i come across with the same issue, any update on this issue?  thanks.

**Comment by paulmaybee** [comment]
We are working on getting the Linux Console to work when in gdb mode. The solution will then be to use gdb mode for debugging on these machines..

**Comment by stanthomas** [comment]
If, as seems to be the case, the issue is related to newer versions of `gdbserver` then "these machines" are pretty soon going to be every Linux distro. Are you giving up on gdbserver?

And do you have any timescale in mind? Will it be possible to get the fix before VS 15.4 is released?

**Comment by robotdad** [comment]
We're not giving up on gdbserver, it's still important. What we're finding is that the gdb client we build and distribute for talking with gdbserver seems to not always be compatible. We're often advising people to switch to gdb mode which is more compatible because it uses the gdb client on the target. Then we run into our linux console doesn't work with that... Once we fix that we intend to switch to gdb mode by default. Gdbserver mode will still be there for targets that don't have a local gdb client. Which of course means we still need to make sure that gdbserver mode works as well.

**Comment by svobodb** [comment]
I'm observing the same ill gdbserver debugging behavior ("Cannot insert breakpoint -1") with gcc 6.3.0 and gdb/gdbserver 7.12.0 on new machine. However gdbserver debugging on old machine with gcc 4.7.2 and gdb/gdbserver 7.4.1 still works fine. "gdb" mode works fine on both machines, unfortunately debugging in "gdb" mode fails when redirecting stdout while "gdbserver" allows the redirecting (OT: please implement stdout/stderr redirecting to an output windows in Linux remote debugging).  I'm using MSVS 15.3.

Downgrading gdb on the new machine from 7.12.0 to 7.4.1 did not help (still "Cannot insert breakpoint -1"). However downgrading gcc from 6.3.0 to 4.7.2 on the new machine **DID help** - I can remotely debug even using gdb 7.12.0. So the problem seems to be caused by the new gcc.

I also noticed that gdb returns 0x0-based addresses (`info address main`) with executables produced by gcc 6.3.0 and 0x400000-base addresses with executables from 4.7.2. Maybe this will point someone responsible to the right direction (different relocation in 6.3.0?).

**Comment by itodirel** [comment]
@lukka assigning this to you, as you fixed this recently

**Comment by lukka** [comment]
Does using GDB mode instead of GDB SERVER mode help?

**Comment by stanthomas** [comment]
@lukka - to whom is your question directed? And, do you have an update on when GDB mode will support the VCLInux console window and, specifically, reading from the command line?

**Comment by lukka** [comment]
@stanthomas VS 15.5 Preview contains the Linux Console I/O redirection for GDB mode for .vcxproj based project, not for CMake ones (that will be 15.6).

**Comment by lukka** [comment]
@svobodb @paulmaybee  I tried to reproduce the issue with VS 15.5 preview 1 with gdb 7.12 and with gcc4.7, gcc6.4.0, gcc7.2.0. In all case I could set breakpoints succesfully. 
If you could help us figuring out how to reproduce the issue about "not being able to set breakpoints" you are welcome, thanks.

**Comment by svobodb** [comment]
VS 15.3: Gdb mode was working fine with both gcc versions. Gdbserver mode worked with gcc 4.7.2 and did not work with gcc 6.3.0.
I needed to use gdbserver mode because gdb mode was discarding stdout and did not allow stdout redirection (attempt to debug using gdb with redirected stdout caused the debugger to hang). Gdbserver mode allowed debugging with stdout redirected.
I will retest with 15.4 and 15.5 preview as soon as I get to a Linux project again.

**Comment by stanthomas** [comment]
I've just tried this in VS 15.5 preview 2 / VCLinux 1.0.8 and Debian 9 Stretch (gcc 6.3.0 gdb 7.12.0).
Debugging in `gdb` mode is working for the following test program:

    std::cout << "enter i0: " << std::endl;
    int i0;
    std::cin >> i0;
    std::cout << "i0 = " << i0 << std::endl;

Program shows prompt, waits for command line input and continues. Can set breakpoints, step thru and inspect values. So looking good.

Linux console window shows (input 121) :

> monaco@jessie-dev:~$ &"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
enter i0: 
121
i0 = 121


If however, the prompt does not have a newline, i.e.

    std::cout << "enter i0: ";

the prompt does not appear before the program waits for input. `gdbserver` mode did.

Also, what is the significance of the GDB warning?

**Comment by lukka** [comment]
@stanthomas thanks for reporting the bug about line ending, it is on our back log. 

Regarding the GDB warning, it is harmless, it is coming from the remote gdb (more info [here](https://github.com/Microsoft/vscode-cpptools/issues/264)). It is anyway on our radar in order to get rid of it.

**Comment by stanthomas** [comment]
@lukka - requiring a line end to flush the buffer to the Linux console seems quite reasonable. So not a bug so much as something that needs to be documented, otherwise folks will be wondering why their program appears to hang when it's really waiting for input.
I've mentioned creating a Wiki on the VClinux site to @robotdad as a place to put these little quirks, I'd be happy to contribute to it as, I'm sure, would many others.

**Comment by odalet** [comment]
Hi, I also encounter similar behavior (though with a different error) when trying to debug a CMake Linux project from VS; here is what gdb says:

```
shellexec 1.0
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-43-Microsoft x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud
 packages can be updated.
 updates are security updates.
Last login: Sat Jan  6 16:40:59 2018 from 127.0.0.1
odalet@PC-OLIVIER:~$ =thread-group-added,id="i1"
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
=cmd-param-changed,param="pagination",value="off"

Breakpoint 1, main (argc=1, argv=0x7ffffffde9b8) at /var/tmp/src/09d4adc1-ad19-843d-9422-7781388af123/Linux-Debug/hello.cpp:6
6	    cout << "Hello" << endl;
Hello

Program received signal SIGTTIN, Stopped (tty input).
0x00007ffffed97230 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:84
Stopped (tty input)

```

The program I try to debug is nothing too fancy:
```C++
#include <iostream>

using namespace std;

int main(int argc, char* argv[]) {
    cout << "Hello" << endl;
    cin.get();
}
```

For the record, I'm using:
* VS 15.5.2, 
* my WSL is still an Ubuntu 16.04.2 LTS. 
* gdb: 7.11.1
* gcc: 54.0

@stanthomas suggested having some Wiki where tricks would be put. It may be a good idea to list configurations (linux distribs, gcc/gdb/vs versions) known to work correctly.

**Comment by lukka** [comment]
@odalet is the error you are referring to `"Stopped (tty input)"` ?
That is fixed in 15.6 or more recent.

**Comment by sameerppradhan** [comment]
Hi,
I am still getting the error for Tizen sample apps project. The error as below while running/debugging.

pkg api_version: 4
=thread-selected,id="1"
Loaded '[vdso]'. Cannot find or open the symbol file.
Loaded 'linux-gate.so.1'. Cannot find or open the symbol file.
The thread 0x1 has exited with code 0 (0x0).
The program 'sdb.exe' has exited with code 0 (0x0).

**Comment by paulmaybee** [comment]
Please collect and attach a log of the gdb session according to the instructions here: https://github.com/Microsoft/MIEngine/wiki/Logging
