### ISSUE TITLE
Remote Headers IntelliSense Manager Questions

### ISSUE THREAD

**Issue by cwm262** [Microsoft/VSLinux#290]
I'm curious about the new remote headers feature. (Caveat: I'm pretty new to Visual Studio.) After downloading the remote headers, were we supposed to be able to leverage these headers without any additional configuration or set-up? With a Linux Makefile project, I seem to have to manually add these to the "include search path" in the project property pages to make use of them. The blog post (https://blogs.msdn.microsoft.com/vcblog/2018/04/09/intellisense-for-remote-linux-headers/) did not show any additional set-up to be able to peek at one of the definitions from a header in the header cache. Does this feature not work with a Makefile project or is there a particular macro that we need to use here?  Thanks!

Also, prior to updating, Visual Studio seemed to be looking into a predefined directory location (e.g.,  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\Linux\include\usr\include\c++\5) to find headers, without any further configuration; that seems to have recently (not sure which version) stopped. I didn't notice anything in the change logs for this. Does anyone have any more information on that? 

Visual Studio Community 2017 Preview (v 15.7.0 preview 5.0)
Visual C++ for Linux Development 1.0.9

**Comment by itodirel** [comment]
this was a bug in Makefiles that we fixed since, pending release

**Comment by cwm262** [comment]
Ok, Thanks @itodirel. Appreciate the work you guys are doing on this

**Comment by itodirel** [comment]
you're most welcome @cwm262 

this will be available in 15.8 Preview 2

**Comment by teknos293** [comment]
Hi, 
Linux dev is a great feature. But I am still unable to make the remote header feature work. I have downloaded the header files successfully, but still have the questions @cwm262 had. Do I need to configure something in the "include search path" for the project? Just selecting the connection does not seem to make intellisense use the automatically downloaded header files. I have tried it both on 15.7.3 and 15.8 Preview 2.

**Comment by huang-tianwen** [comment]
@teknos293 i am facing similar problem, downloaded the header files but intellisense still give me error cannot open source file cstdio. but can compile. Using Visual Studio Community 2017 version 15.8.2

**Comment by nohajc** [comment]
@itodirel I am not sure what was fixed. The need to explicitly add copied headers to "include search path" or the inability to use the bundled headers instead?

I would very much appreciate to have both options. The predefined directory mentioned by @cwm262 works for me (in 15.5) will I be able to still somehow use it in the more recent Visual Studio versions?

Thanks

**Comment by samuelagm** [comment]
@itodirel  I just downloaded VS 2019 RC after having no luck with vs 2017, and the intellisense issue is still there.  The header files sync is successful after connecting to a remote host, but the intellisense doesn't work thereafter

I manually added `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\include\usr\include\c++\5` to the VC++ Include directories and the include errors have gone, but baisc functions like cout and printf cannot be found by intellisense.

**Comment by samuelagm** [comment]
> @itodirel I just downloaded VS 2019 RC after having no luck with vs 2017, and the intellisense issue is still there. The header files sync is successful after connecting to a remote host, but the intellisense doesn't work thereafter
> 
> I manually added `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\include\usr\include\c++\5` to the VC++ Include directories and the include errors have gone, but baisc functions like cout and printf cannot be found by intellisense.

Restarting my computer and creating an empty project fixed the problem.

**Comment by range4life** [comment]
For me, deleting the intellisense cache (or just deleting the whole .vs folder) worked.
