### ISSUE TITLE
C++17 IntelliSense does not work with Makefile project

### ISSUE THREAD

**Issue by bobroberts177** [Microsoft/VSLinux#292]
* A brief description

It does not seem to be possible to set the C++ version for IntelliSense for a Makefile project.  I have tried setting "/std:c++17" in "Properties -> C/C++ -> IntelliSense -> Additional Options" but it has no effect.

* Expected results

This line should not result in an IntelliSense error when the flag is set:

```
int foo() { return 1'000; }
```

(Note that it correctly does not result in an IntelliSense error on a Console Application if the "Properties -> C/C++ -> Language -> C++ Language Standard" is set to "C++17")

* Actual results (with build output window contents if applicable)

`Error (active)	E0008	missing closing quote`

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

```
Microsoft Visual Studio Community 2017 Preview
Version 15.8.0 Preview 1.1
VisualStudio.15.Preview/15.8.0-pre.1.1+27705.2000
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA905
Microsoft Visual C++ 2017

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development
```

* Steps required to reproduce the error

Create a new Makefile Project (Linux), add above mentioned flag and code

* Required packages and commands to install

Nothing except the obvious

**Comment by itodirel** [comment]
we fixed this now, and it's going to be available in 15.8 Preview 3

**Comment by swilliamshft** [comment]
How do you activate this functionality?  I tried adding /std:c++17 to C/C++ -> Intellisense -> Additional Options but "auto q = 1'000;" still shows squiggly for me.  I am on 15.9.27.

**Comment by swilliamshft** [comment]
![Project1](https://user-images.githubusercontent.com/44142709/93734857-961c5600-fba0-11ea-9c96-0db5ca609714.png)

**Comment by swilliamshft** [comment]
@itodirel .

**Comment by paulmaybee** [comment]
You'll need to move forward to a later version of Visual Studio to get the feature. The intellisense property pages now include specific fields for the language version.
![image](https://user-images.githubusercontent.com/12514776/93792860-ecae8200-fbea-11ea-98c4-e43eaee22933.png)

**Comment by swilliamshft** [comment]
Okay......thanks.

**Comment by swilliamshft** [comment]
For anyone else reading this, I took the values from my VS2019 project and hand-edited them into my VS2017 project and this appears to work:

```
   <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
     <!-- .... -->
     <ClCompile>
       <CppLanguageStandard>c++17</CppLanguageStandard>
     </ClCompile>
   </ItemDefinitionGroup>
```
