### ISSUE TITLE
Files not being copied remotely

### ISSUE THREAD

**Issue by zbagz** [microsoft/VSLinux#369]
Files are not being copied to the remote machine on a makefile linux project. 

This is happening on VisualStudio.16.Preview/16.0.0-pre.4.2+28711.60 and Visual C++ for Linux Development   1.0.9.28711.

However, the same project synchronizes just fine when running on VisualStudio.15.Release/15.9.9+28307.518 and Visual C++ for Linux Development   1.0.9.28218.

Still... I cannot use Visual Studio 15 since there's also a bug with makefile projects described in #355.

**Comment by itodirel** [comment]
Hi, can you tell me how are you copying files and what is the error you are seeing? Are these files part of the project, or are you using pre-build/post-build events?

**Comment by zbagz** [comment]
Nothing specific. This is a project created on Visual Studio 15, and when opened in Visual Studio 16 the build process does not work since the files are not being copied before trying to build or execute the remote build command.

Yes, the files are part of the project.

As a workaround, I've downgraded to version 15.8.9 as it appears to work just fine with linux makefile projects.

**Comment by Telboy99** [comment]
So I am also having the same issue. I have tried downloading VS 2019 and that fails as well.

I get the error 'Invalid URI: The format of the URI could not be determined' 

This was working on older VS 2017, I will try and downgrade if I still have a copy of 15.8.9

**Comment by tianxingyang** [comment]
Same issue. Mine is easy to reproduce.

1. Create a new makefile(linux) project.
2. add main.cpp to project.
3. set build command line in remote build: cd ~/test; g++ main.cpp -o main.o
4. set remote build root directory in General: ~/test
5. set Configuration Type in General: Makefile
6. set Copy Sources: yes
7. click build
8. no copy operation would show up, so that the build operation would fail.

The version of VS is 16.0.0.

**Comment by thomasmaters** [comment]
Same issue, also with the steps described in @tianxingyang's post.
Looking in the verbose output I noticed '_CopySources' target not being executed.

So to temporary fix the issue, I added the '_CopySources' target as a 'DependsOnTarget' item for the 'RemotePreBuildEvent' target. 
This edit was done in the file _Linux.Makefile.targets_ (located here: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.Makefile.targets).

So the line looks like this, after my edit:
`  <Target Name="RemotePreBuildEvent" Condition="'$(RemotePreBuildEventUseInBuild)' != 'false'" DependsOnTargets="ResolveRemoteDir;_ResolveRemoteTarget;ResolveRemoteDir;_RequiresRemoteConnection;_CopySources">`
After that I did a "Rebuild" and it worked.

I hope this will help some people, in the time before a permanent fix.

VS version: 16.0.1
Visual C++ for Linux Development:   1.0.9.28711

**Comment by itodirel** [comment]
Hi, we have identified this issue and fixed it, the fix will be available in 16.1 Preview 2

**Comment by itodirel** [comment]
This has been fixed. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Comment by yundorri** [comment]
In my case, I tried as mentioned in 
https://developercommunity.visualstudio.com/t/2019-makefile-project-doesnt-copy-source-on-build/447310
but not solved and I solved by deleting the 'obj' folder in solution folder.

After deleting obj folder, visual studio copied all of source files keeps folder sturctures.
