### ISSUE TITLE
Remote GDB Debugger use shellexec.exe, but never exit

### ISSUE THREAD

**Issue by avalon1610** [Microsoft/VSLinux#81]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
After use Remote GDB Debugger, I found shellexec.exe was never exit.
there will be many shellexec process running after debug several times.
It' s also keep ssh connection, cause I can not login in to linux server when  server has some limit.
* Expected results
shellexec.exe exit after debug
* Actual results (with build output window contents if applicable)
shellexec.exe did not exit, keep running
* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual Studio 2017 RC,  GCC 6.2.0
* Steps required to reproduce the error

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment]
I'm currently working on a fix for this, thanks for reporting.

**Comment by itodirel** [comment]
This is now fixed, and it will be available as soon as the next release.

**Comment by adsamcik** [comment]
This issue is still present in VS 2017 release.

**Comment by Vicente-Hernandez-Segura** [comment]
Like adsamcik said this issue is still present in Visual Studio 2007.

**Comment by robotdad** [comment]
@avalon1610 @Vicente-Hernandez-Segura @adsamcik have you been able to try this in more recent builds of VS 2017?

@itodirel can you confirm this is in 15.2 or 15.3? 1.0.7 is 15.3 but this is tagged 15.2

**Comment by itodirel** [comment]
this will be in 15.3, which is not out yet, and is currently in 1.0.7

**Comment by lukka** [comment]
Closing this issue, please feel free to reopen the issue with a repro on the most recent version of Visual Studio 2017, thanks.
